version: '3'
services:
    webfm:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '8564:8564'
        environment:
            - dataDir=/usr/src/webrain/data
            - PORT=8564
        volumes:
            - $webrainDir:/usr/src/webrain
            - $webfmDataDir:/usr/src/webrain/data
        tty: true
