#!/bin/bash

workdir='/home'

$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0001.srf > $SUBJECTS_DIR/$1/obj/rh.bankssts.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0002.srf > $SUBJECTS_DIR/$1/obj/rh.caudalanteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0003.srf > $SUBJECTS_DIR/$1/obj/rh.caudalmiddlefrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0004.srf > $SUBJECTS_DIR/$1/obj/rh.corpuscallosum.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0005.srf > $SUBJECTS_DIR/$1/obj/rh.cuneus.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0006.srf > $SUBJECTS_DIR/$1/obj/rh.entorhinal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0007.srf > $SUBJECTS_DIR/$1/obj/rh.fusiform.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0008.srf > $SUBJECTS_DIR/$1/obj/rh.inferiorparietal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0009.srf > $SUBJECTS_DIR/$1/obj/rh.inferiortemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0010.srf > $SUBJECTS_DIR/$1/obj/rh.isthmuscingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0011.srf > $SUBJECTS_DIR/$1/obj/rh.lateraloccipital.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0012.srf > $SUBJECTS_DIR/$1/obj/rh.lateralorbitofrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0013.srf > $SUBJECTS_DIR/$1/obj/rh.lingual.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0014.srf > $SUBJECTS_DIR/$1/obj/rh.medialorbitofrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0015.srf > $SUBJECTS_DIR/$1/obj/rh.middletemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0016.srf > $SUBJECTS_DIR/$1/obj/rh.parahippocampal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0017.srf > $SUBJECTS_DIR/$1/obj/rh.paracentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0018.srf > $SUBJECTS_DIR/$1/obj/rh.parsopercularis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0019.srf > $SUBJECTS_DIR/$1/obj/rh.parsorbitalis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0020.srf > $SUBJECTS_DIR/$1/obj/rh.parstriangularis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0021.srf > $SUBJECTS_DIR/$1/obj/rh.pericalcarine.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0022.srf > $SUBJECTS_DIR/$1/obj/rh.postcentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0023.srf > $SUBJECTS_DIR/$1/obj/rh.posteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0024.srf > $SUBJECTS_DIR/$1/obj/rh.precentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0025.srf > $SUBJECTS_DIR/$1/obj/rh.precuneus.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0026.srf > $SUBJECTS_DIR/$1/obj/rh.rostralanteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0027.srf > $SUBJECTS_DIR/$1/obj/rh.rostralmiddlefrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0028.srf > $SUBJECTS_DIR/$1/obj/rh.superiorfrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0029.srf > $SUBJECTS_DIR/$1/obj/rh.superiorparietal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0030.srf > $SUBJECTS_DIR/$1/obj/rh.superiortemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0031.srf > $SUBJECTS_DIR/$1/obj/rh.supramarginal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0032.srf > $SUBJECTS_DIR/$1/obj/rh.frontalpole.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0033.srf > $SUBJECTS_DIR/$1/obj/rh.temporalpole.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0034.srf > $SUBJECTS_DIR/$1/obj/rh.transversetemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/rh.pial_roi.0035.srf > $SUBJECTS_DIR/$1/obj/rh.insula.obj

$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0001.srf > $SUBJECTS_DIR/$1/obj/lh.bankssts.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0002.srf > $SUBJECTS_DIR/$1/obj/lh.caudalanteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0003.srf > $SUBJECTS_DIR/$1/obj/lh.caudalmiddlefrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0004.srf > $SUBJECTS_DIR/$1/obj/lh.corpuscallosum.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0005.srf > $SUBJECTS_DIR/$1/obj/lh.cuneus.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0006.srf > $SUBJECTS_DIR/$1/obj/lh.entorhinal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0007.srf > $SUBJECTS_DIR/$1/obj/lh.fusiform.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0008.srf > $SUBJECTS_DIR/$1/obj/lh.inferiorparietal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0009.srf > $SUBJECTS_DIR/$1/obj/lh.inferiortemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0010.srf > $SUBJECTS_DIR/$1/obj/lh.isthmuscingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0011.srf > $SUBJECTS_DIR/$1/obj/lh.lateraloccipital.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0012.srf > $SUBJECTS_DIR/$1/obj/lh.lateralorbitofrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0013.srf > $SUBJECTS_DIR/$1/obj/lh.lingual.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0014.srf > $SUBJECTS_DIR/$1/obj/lh.medialorbitofrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0015.srf > $SUBJECTS_DIR/$1/obj/lh.middletemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0016.srf > $SUBJECTS_DIR/$1/obj/lh.parahippocampal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0017.srf > $SUBJECTS_DIR/$1/obj/lh.paracentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0018.srf > $SUBJECTS_DIR/$1/obj/lh.parsopercularis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0019.srf > $SUBJECTS_DIR/$1/obj/lh.parsorbitalis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0020.srf > $SUBJECTS_DIR/$1/obj/lh.parstriangularis.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0021.srf > $SUBJECTS_DIR/$1/obj/lh.pericalcarine.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0022.srf > $SUBJECTS_DIR/$1/obj/lh.postcentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0023.srf > $SUBJECTS_DIR/$1/obj/lh.posteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0024.srf > $SUBJECTS_DIR/$1/obj/lh.precentral.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0025.srf > $SUBJECTS_DIR/$1/obj/lh.precuneus.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0026.srf > $SUBJECTS_DIR/$1/obj/lh.rostralanteriorcingulate.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0027.srf > $SUBJECTS_DIR/$1/obj/lh.rostralmiddlefrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0028.srf > $SUBJECTS_DIR/$1/obj/lh.superiorfrontal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0029.srf > $SUBJECTS_DIR/$1/obj/lh.superiorparietal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0030.srf > $SUBJECTS_DIR/$1/obj/lh.superiortemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0031.srf > $SUBJECTS_DIR/$1/obj/lh.supramarginal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0032.srf > $SUBJECTS_DIR/$1/obj/lh.frontalpole.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0033.srf > $SUBJECTS_DIR/$1/obj/lh.temporalpole.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0034.srf > $SUBJECTS_DIR/$1/obj/lh.transversetemporal.obj
$workdir/scripts/octave/srf2obj $SUBJECTS_DIR/$1/rois/lh.pial_roi.0035.srf > $SUBJECTS_DIR/$1/obj/lh.insula.obj
