# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinxcontrib-openapi
          rm -r docs/ReconViz/build
          sphinx-build -b html docs/ReconViz/source docs/ReconViz/build
          sphinx-build -b html docs/Localization/source docs/Localization/build
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to docker (gen)
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: generate.Dockerfile
          tags: neuroseek/3d_reconstruction:latest

      - name: Push to docker (viz)
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: visualize.Dockerfile
          tags: neuroseek/recon_visualizer:latest